# wix3 toolset build pipeline

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0A' -Name InstallationFolder
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.2' -Name InstallationFolder
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1' -Name InstallationFolder
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1A' -Name InstallationFolder
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A' -Name InstallationFolder
      Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A' -Name InstallationFolder
    errorActionPreference: 'continue'
- task: MSBuild@1
  displayName: Initialize build
  inputs:
    solution: 'tools\OneTimeWixBuildInitialization.proj'
    msbuildArguments: '/v:diag'
    msbuildVersion: '15.0'
    platform: 'AnyCPU'
    configuration: 'Release'
    createLogFile: true
    logFileVerbosity: 'diagnostic'

- task: MSBuild@1
  displayName: Report build diagnostics information
  inputs:
    solution: 'wix.proj'
    msbuildArguments: '/t:Diagnostics'
    logFileVerbosity: 'normal'


- task: MSBuild@1
  displayName: Build wix3 toolset
  inputs:
    solution: 'wix.proj'
    msbuildVersion: '15.0'
    platform: 'AnyCPU'
    configuration: 'Release'
    msbuildArguments: '/t:Build'
    createLogFile: true
    logFileVerbosity: 'normal'