<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>candle</AssemblyName>
    <RootNamespace>Microsoft.Tools.WindowsInstallerXml.Tools</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);SYSLIB0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../tools/candle/*.cs" Exclude="../../tools/candle/AssemblyInfo.cs" />
    <EmbeddedResource Include="../../tools/candle/CandleStrings.resx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Wix.Legacy.Console/Wix.Legacy.Console.csproj" />
    <ProjectReference Include="../Wix.Legacy.Core/Wix.Legacy.Core.csproj" />
  </ItemGroup>
</Project>
