<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>xsdgen</AssemblyName>
    <RootNamespace>Microsoft.Tools.WindowsInstallerXml.Tools</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS0618;SYSLIB0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../../tools/src/XsdGen/*.cs" Exclude="../../../tools/src/XsdGen/AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="10.0.0" />
  </ItemGroup>
</Project>
